"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { format } from "date-fns";
import { id } from "date-fns/locale";
import {
    Calendar, Check, X, Video, LogOut, Clock,
    User, FileText, MessageSquare
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";

type Booking = {
    id: number;
    client_name: string;
    client_contact: string;
    complaint: string;
    schedule_time: string;
    status: "pending" | "approved" | "rejected" | "completed";
    room_id: string;
    session_notes?: string;
};

export default function ExpertDashboard() {
    const router = useRouter();
    const [bookings, setBookings] = useState<Booking[]>([]);
    const [loading, setLoading] = useState(true);
    const [expertName, setExpertName] = useState("");

    useEffect(() => {
        // Check Auth (Mock)
        const token = localStorage.getItem("expert_token");
        const email = localStorage.getItem("expert_email");

        if (!token) {
            router.push("/login");
            return;
        }

        if (email) setExpertName(email);

        fetchBookings();
    }, [router]);

    const fetchBookings = async () => {
        try {
            const protocol = window.location.protocol;
            const host = window.location.hostname;
            const email = localStorage.getItem("expert_email") || "";

            // IMPORTANT: Pass email to filter bookings by this psychologist only
            const res = await fetch(`${protocol}//${host}:8080/api/expert/bookings?email=${encodeURIComponent(email)}`);
            if (res.ok) {
                const data = await res.json();
                setBookings(data || []);
            }
        } catch (err) {
            console.error("Failed to fetch bookings:", err);
        } finally {
            setLoading(false);
        }
    };

    const handleStatusUpdate = async (id: number, status: "approved" | "rejected") => {
        if (!confirm(`Apakah anda yakin ingin mengubah status menjadi ${status}?`)) return;

        try {
            const protocol = window.location.protocol;
            const host = window.location.hostname;
            const res = await fetch(`${protocol}//${host}:8080/api/expert/bookings/${id}/status`, {
                method: "PUT",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ status }),
            });

            if (res.ok) {
                // Optimistic Update
                setBookings(prev => prev.map(b => b.id === id ? { ...b, status } : b));

                // If approved, we might need to reload to get the room_id generated by backend
                if (status === "approved") {
                    setTimeout(fetchBookings, 500);
                }
            }
        } catch (err) {
            alert("Gagal mengupdate status");
        }
    };

    const handleLogout = () => {
        localStorage.removeItem("expert_token");
        router.push("/");
    };

    const pendingBookings = bookings.filter(b => b.status === "pending");
    const upcomingBookings = bookings.filter(b => b.status === "approved");
    const pastBookings = bookings.filter(b => b.status === "completed" || b.status === "rejected");

    return (
        <main className="min-h-screen bg-slate-950 p-6">
            <div className="max-w-6xl mx-auto">
                {/* Header */}
                <header className="flex items-center justify-between mb-8 sticky top-0 bg-slate-950/80 backdrop-blur-md z-10 py-4 border-b border-slate-800">
                    <div>
                        <h1 className="text-2xl font-bold text-white">Dashboard Psikolog</h1>
                        <p className="text-slate-400">Kelola jadwal dan sesi konsultasi Anda.</p>
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="text-right hidden md:block">
                            <p className="text-white font-medium">
                                {expertName || "Expert"}
                            </p>
                            <p className="text-xs text-emerald-400">● Online</p>
                        </div>
                        <button
                            onClick={handleLogout}
                            className="bg-slate-800 hover:bg-slate-700 text-slate-300 p-2 rounded-lg transition-colors"
                            title="Keluar"
                        >
                            <LogOut size={20} />
                        </button>
                    </div>
                </header>

                {/* Grid Layout */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

                    {/* Left Column: Requests & Upcoming */}
                    <div className="lg:col-span-2 space-y-8">

                        {/* Pending Requests */}
                        <section>
                            <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                                <User className="text-yellow-400" size={20} />
                                Permintaan Masuk <span className="text-xs bg-yellow-500/20 text-yellow-400 px-2 py-0.5 rounded-full">{pendingBookings.length}</span>
                            </h2>

                            <div className="space-y-4">
                                <AnimatePresence>
                                    {pendingBookings.length === 0 ? (
                                        <div className="text-slate-500 italic text-sm">Tidak ada permintaan baru.</div>
                                    ) : (
                                        pendingBookings.map(booking => (
                                            <motion.div
                                                key={booking.id}
                                                initial={{ opacity: 0, height: 0 }}
                                                animate={{ opacity: 1, height: "auto" }}
                                                exit={{ opacity: 0, height: 0 }}
                                                className="bg-slate-900 border border-slate-800 p-6 rounded-xl shadow-lg"
                                            >
                                                <div className="flex justify-between items-start mb-4">
                                                    <div>
                                                        <h3 className="text-white font-bold text-lg">{booking.client_name}</h3>
                                                        <p className="text-slate-400 text-sm">{booking.client_contact}</p>
                                                    </div>
                                                    <span className="text-xs bg-slate-800 px-3 py-1 rounded-full text-slate-400 border border-slate-700">
                                                        Pending
                                                    </span>
                                                </div>

                                                <div className="bg-slate-950/50 p-3 rounded-lg border border-slate-800/50 mb-4">
                                                    <p className="text-slate-300 text-sm italic">"{booking.complaint}"</p>
                                                </div>

                                                <div className="flex items-center justify-between">
                                                    <div className="flex items-center gap-2 text-sky-400 text-sm font-medium">
                                                        <Clock size={16} />
                                                        {format(new Date(booking.schedule_time), "EEEE, dd MMMM - HH:mm", { locale: id })}
                                                    </div>

                                                    <div className="flex gap-2">
                                                        <button
                                                            onClick={() => handleStatusUpdate(booking.id, "rejected")}
                                                            className="px-4 py-2 rounded-lg border border-red-500/30 text-red-400 hover:bg-red-500/10 text-sm font-medium transition-colors"
                                                        >
                                                            Tolak
                                                        </button>
                                                        <button
                                                            onClick={() => handleStatusUpdate(booking.id, "approved")}
                                                            className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium shadow-lg shadow-emerald-600/20 flex items-center gap-2 transition-colors"
                                                        >
                                                            <Check size={16} /> Setujui
                                                        </button>
                                                    </div>
                                                </div>
                                            </motion.div>
                                        ))
                                    )}
                                </AnimatePresence>
                            </div>
                        </section>

                        {/* Upcoming Sessions */}
                        <section>
                            <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                                <Video className="text-sky-400" size={20} />
                                Jadwal Akan Datang
                            </h2>

                            <div className="space-y-4">
                                {upcomingBookings.length === 0 ? (
                                    <div className="text-slate-500 italic text-sm">Belum ada jadwal disetujui.</div>
                                ) : (
                                    upcomingBookings.map(booking => (
                                        <div key={booking.id} className="bg-slate-900 border border-l-4 border-l-sky-500 border-slate-800 p-6 rounded-xl flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                                            <div>
                                                <h3 className="text-white font-bold">{booking.client_name}</h3>
                                                <div className="flex items-center gap-2 text-slate-400 text-sm mt-1">
                                                    <Clock size={14} />
                                                    {format(new Date(booking.schedule_time), "dd MMM yyyy, HH:mm", { locale: id })}
                                                </div>
                                                <div className="flex items-center gap-2 text-slate-500 text-xs mt-2">
                                                    <FileText size={12} />
                                                    {booking.complaint}
                                                </div>
                                            </div>

                                            <Link
                                                href={`/session?room=${booking.room_id}`}
                                                className="w-full sm:w-auto px-5 py-2.5 bg-sky-600 hover:bg-sky-500 text-white rounded-lg font-medium shadow-lg shadow-sky-600/20 flex items-center justify-center gap-2 transition-colors"
                                            >
                                                <Video size={18} /> Masuk Room
                                            </Link>
                                        </div>
                                    ))
                                )}
                            </div>
                        </section>
                    </div>

                    {/* Right Column: History / Notes */}
                    <div className="space-y-6">
                        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                            <h2 className="text-white font-semibold mb-4">Ringkasan</h2>
                            <div className="grid grid-cols-2 gap-4">
                                <div className="bg-slate-950 p-4 rounded-lg text-center">
                                    <div className="text-2xl font-bold text-emerald-400">{upcomingBookings.length}</div>
                                    <div className="text-xs text-slate-500">Upcoming</div>
                                </div>
                                <div className="bg-slate-950 p-4 rounded-lg text-center">
                                    <div className="text-2xl font-bold text-slate-300">{pastBookings.length}</div>
                                    <div className="text-xs text-slate-500">Selesai</div>
                                </div>
                            </div>
                        </div>

                        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 h-fit max-h-[500px] overflow-y-auto custom-scrollbar">
                            <h2 className="text-white font-semibold mb-4 text-sm uppercase tracking-wider text-slate-400">Riwayat Terakhir</h2>
                            <div className="space-y-3">
                                {pastBookings.slice(0, 5).map(b => (
                                    <div key={b.id} className="text-sm border-b border-slate-800 pb-3 last:border-0 last:pb-0">
                                        <div className="flex justify-between mb-1">
                                            <span className="text-slate-300 font-medium">{b.client_name}</span>
                                            <span className={`text-xs px-2 py-0.5 rounded ${b.status === 'rejected' ? 'text-red-400 bg-red-400/10' : 'text-slate-400 bg-slate-800'}`}>
                                                {b.status}
                                            </span>
                                        </div>
                                        <div className="text-xs text-slate-500">
                                            {format(new Date(b.schedule_time), "dd/MM/yyyy", { locale: id })}
                                        </div>
                                    </div>
                                ))}
                                {pastBookings.length === 0 && <span className="text-xs text-slate-600">Belum ada riwayat.</span>}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </main>
    );
}
